language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - COMPOSER_OPTIONS="--prefer-source"
  - COMPOSER_OPTIONS="--prefer-source --prefer-lowest"

install:
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PWD/bin:/tmp/local/bin:$PWD/tests/fixtures:$PATH
  - composer update $COMPOSER_OPTIONS

script:
  - bats --version
  - bats tests

notifications:
  email: false
