#!/bin/sh
_%%SCRIPT%%()
{
    local cur prev coms opts
    COMPREPLY=()
    _get_comp_words_by_ref -n : cur prev cword
    coms="%%COMMANDS%%"
    opts="%%SHARED_OPTIONS%%"

    if [[ $cword = 1 ]] ; then
        COMPREPLY=($(compgen -W "${coms}" -- ${cur}))
        __ltrim_colon_completions "$cur"
        return 0
    fi

    case "${prev}" in
        %%SWITCH_CONTENT%%
        esac

    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
    return 0;
}

complete -o default -F _%%SCRIPT%% %%SCRIPT%%
